from pathlib import Path
from torch import multiprocessing
from tqdm import tqdm
import soundfile as sf

import numpy as np
import pandas as pd
import time

import sys

# append the path of the
# parent directory
sys.path.append('..')
sys.path.append(f'{Path(__file__).parent}/../src/')
sys.path.append(f'{Path(__file__).parent}/../src/models/bat_call_detector/batdetect2/')
print(sys.path)

import batdt2_pipeline as batdetect2_pipeline
from pipeline import pipeline
from utils.utils import gen_empty_df
from cfg import get_config


def run_models(file_mappings):
    """
    Runs the batdetect2 model to detect bat search-phase calls in the provided audio segments and saves detections into a .csv.

    Parameters
    ------------
    file_mappings : `List`
        - List of dictionaries generated by initialize_mappings()

    Returns
    ------------
    bd_dets : `pandas.DataFrame`
        - A DataFrame of detections that will also be saved in the provided output_dir under the above csv_name
        - 7 columns in this DataFrame: start_time, end_time, low_freq, high_freq, detection_confidence, event, input_file
        - Detections are always specified w.r.t their input_file; earliest start_time can be 0 and latest end_time can be 1795.
        - Events are always "Echolocation" as we are using a model that only detects search-phase calls.
    """

    bd_dets = pd.DataFrame()
    for i in tqdm(range(len(file_mappings))):
        cur_seg = file_mappings[i]
        bd_annotations_df = cur_seg['model']._run_batdetect(cur_seg['audio_seg']['audio_file'])
        bd_offsetted = pipeline._correct_annotation_offsets(
                bd_annotations_df,
                cur_seg['original_file_name'],
                cur_seg['audio_seg']['offset']
            )
        bd_dets = pd.concat([bd_dets, bd_offsetted])
        
    return bd_dets

def apply_model(file_mapping):
    """
    Runs the batdetect2 model on a single provided audio segmens and corrects the offsets according the segment.

    Parameters
    ------------
    file_mappings : `List`
        - List of dictionaries generated by initialize_mappings()

    Returns
    ------------
    corrected_bd_dets : `pandas.DataFrame`
        - A DataFrame of detections that will also be saved in the provided output_dir under the above csv_name
        - 7 columns in this DataFrame: start_time, end_time, low_freq, high_freq, detection_confidence, event, input_file
        - Detections are always specified w.r.t their input_file; earliest start_time can be 0 and latest end_time can be 1795.
        - Events are always "Echolocation" as we are using a model that only detects search-phase calls.
    """

    bd_dets = file_mapping['model']._run_batdetect(file_mapping['audio_seg']['audio_file'])
    corrected_bd_dets = pipeline._correct_annotation_offsets(
                                                            bd_dets,
                                                            file_mapping['original_file_name'],
                                                            file_mapping['audio_seg']['offset']
                                                            )

    return corrected_bd_dets

if __name__ == '__main__':

    input_file = Path(f'{Path(__file__).parent}/../../Downloads/recover-20220728/Carp/20220728_080000.WAV')

    cfg = get_config()
    cfg['input_audio'] = input_file
    cfg['tmp_dir'] = Path('../output')
    cfg['output_dir'] = Path('../output_dir')
    cfg['run_model'] = True
    cfg['should_csv'] = False
    cfg['save'] = False

    # apply_pipeline_on_file(input_file, cfg)
    bd_preds = pd.DataFrame()

    if not cfg['output_dir'].is_dir():
        cfg['output_dir'].mkdir(parents=True, exist_ok=True)
    if not cfg['tmp_dir'].is_dir():
        cfg['tmp_dir'].mkdir(parents=True, exist_ok=True)

    cfg["csv_filename"] = f"batdetect2_pipeline_{input_file.name.split('.')[0]}"
    print(f"Generating detections for {input_file.name}")
    segmented_file_paths = batdetect2_pipeline.generate_segmented_paths([input_file], cfg)
    file_path_mappings = batdetect2_pipeline.initialize_mappings(segmented_file_paths, cfg)
    
    input = file_path_mappings[:4]
    for i in np.arange(multiprocessing.cpu_count()):
        cfg['num_processes'] = int(i+1)
        with multiprocessing.Pool(processes=cfg['num_processes']) as pool:
            chunksize_custom = 2
            print(f"Parsing {len(input)} chunks with {cfg['num_processes']} processors and {chunksize_custom} chunks per processor")
            start = time.time()
            results = pool.map(apply_model, input, chunksize=chunksize_custom)
            bd_preds = gen_empty_df() 
            bd_preds = pd.concat(results, ignore_index=True)
            end = time.time()
            print(f'Time taken: {end-start}s')