from pathlib import Path
from torch import multiprocessing
import torch
from tqdm import tqdm
import soundfile as sf

import numpy as np
import pandas as pd
import time

import matplotlib.pyplot as plt

import sys

# append the path of the
# parent directory
sys.path.append('..')
sys.path.append(f'{Path(__file__).parent}/../src/')
sys.path.append(f'{Path(__file__).parent}/../src/models/bat_call_detector/batdetect2/')

import batdt2_pipeline as batdetect2_pipeline
from pipeline import pipeline
from utils.utils import gen_empty_df
from cfg import get_config


def run_models(file_mappings):
    """
    Runs the batdetect2 model to detect bat search-phase calls in the provided audio segments and saves detections into a .csv.

    Parameters
    ------------
    file_mappings : `List`
        - List of dictionaries generated by initialize_mappings()

    Returns
    ------------
    bd_dets : `pandas.DataFrame`
        - A DataFrame of detections that will also be saved in the provided output_dir under the above csv_name
        - 7 columns in this DataFrame: start_time, end_time, low_freq, high_freq, detection_confidence, event, input_file
        - Detections are always specified w.r.t their input_file; earliest start_time can be 0 and latest end_time can be 1795.
        - Events are always "Echolocation" as we are using a model that only detects search-phase calls.
    """

    bd_dets = pd.DataFrame()
    for i in tqdm(range(len(file_mappings))):
        cur_seg = file_mappings[i]
        bd_annotations_df = cur_seg['model']._run_batdetect(cur_seg['audio_seg']['audio_file'])
        bd_offsetted = pipeline._correct_annotation_offsets(
                bd_annotations_df,
                cur_seg['original_file_name'],
                cur_seg['audio_seg']['offset']
            )
        bd_dets = pd.concat([bd_dets, bd_offsetted])
        
    return bd_dets

def _apply_model(item):
    annotations_df = item['model']._run_batdetect(item['audio_seg']['audio_file'])
    return pipeline._correct_annotation_offsets(
        annotations_df,
        item['original_file_name'],
        item['audio_seg']['offset']
    )

def _apply_models(cfg, audio_segments):
    csv_names = []
    audio_file_path = cfg['audio_file']
    process_pool = multiprocessing.Pool(cfg['num_processes'])

    for model in cfg['models']:

        l_for_mapping = [{
            'audio_seg': audio_seg, 
            'model': model,
            'original_file_name': audio_file_path,
            } for audio_seg in audio_segments]

        pred_dfs = tqdm(
            process_pool.imap(_apply_model, l_for_mapping, chunksize=1), 
            desc=f"Applying {model.get_name()}",
            total=len(l_for_mapping),
        )

        agg_df = gen_empty_df() 
        agg_df = pd.concat(pred_dfs, ignore_index=True)

        csv_name = pipeline._generate_csv(agg_df, model.get_name(),
            audio_file_path.name,
            cfg['output_dir'],
            cfg['should_csv']
        )
        csv_names.append(csv_name)

    return csv_names

if __name__ == '__main__':
    multiprocessing.set_start_method('spawn')
    input_file = Path(f'{Path(__file__).parent}/../../Downloads/recover-20220728/Carp/20220728_080000.WAV')

    cfg = get_config()
    cfg['audio_file'] = input_file
    cfg['tmp_dir'] = Path('../output')
    cfg['output_dir'] = Path('../output_dir')
    cfg['num_processes'] = 16
    cfg['should_csv'] = False
    cfg['save'] = True

    if not cfg['output_dir'].is_dir():
        cfg['output_dir'].mkdir(parents=True, exist_ok=True)
    if not cfg['tmp_dir'].is_dir():
        cfg['tmp_dir'].mkdir(parents=True, exist_ok=True)

    cfg["csv_filename"] = f"batdetect2_pipeline_{input_file.name.split('.')[0]}"
    print(f"Generating detections for {input_file.name}")
    segmented_file_paths = batdetect2_pipeline.generate_segmented_paths([input_file], cfg)
    file_path_mappings = batdetect2_pipeline.initialize_mappings(segmented_file_paths, cfg)
    input = file_path_mappings[:]
    num_rows = min(len(input), multiprocessing.cpu_count())
    num_cols = multiprocessing.cpu_count()
    time_taken_test3 = np.zeros((num_rows, num_cols))
    for i in range(num_rows):
        for j in range(num_cols):
            num_processes = int(i+1)
            default_num_threads_per_processor = torch.get_num_threads() # np.floor(multiprocessing.cpu_count()/num_processes).astype(int)
            num_threads_per_processor = np.floor(multiprocessing.cpu_count()/num_processes).astype(int)
            if num_threads_per_processor!=default_num_threads_per_processor:
                torch.set_num_threads(num_threads_per_processor)
            pool = multiprocessing.Pool(processes=num_processes)
            chunksize_custom = int(j+1)
            print(f'Parsing {len(input)} chunks with {num_processes} processors and {chunksize_custom} chunksize and {num_threads_per_processor} threads per processor')
            start = time.time()
            results = tqdm(pool.imap(_apply_model, input, chunksize=chunksize_custom), 
                            desc=f"Applying BatDetect2", total=len(input),)
            bd_preds = gen_empty_df() 
            bd_preds = pd.concat(results, ignore_index=True)
            end = time.time()
            time_taken_test3[i,j] = end-start

    plt.figure(figsize=(8,6))
    plt.title(f'{len(input)} segments fixed; num_threads=1')
    plt.imshow(time_taken_test3)
    plt.ylabel('Num_processes (processors assigned)')
    plt.xlabel('Chunksize (chunks per processor)')
    plt.yticks(np.arange(num_rows)-0.5, np.arange(num_rows)+1)
    plt.xticks(np.arange(num_cols)-0.5, np.arange(num_cols)+1)
    plt.grid(which='both')
    plt.colorbar(label='Time taken (s)')
    plt.savefig(f'20241105__large_instance_single_file_computation.png')
