import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

import time
from pathlib import Path

import soundfile as sf
import torch
from tqdm import tqdm
from torch import multiprocessing

import sys

# append the path of the
# parent directory
sys.path.append(f'{Path(__file__).parent}/..')
sys.path.append(f'{Path(__file__).parent}/../src/')
sys.path.append(f'{Path(__file__).parent}/../src/models/bat_call_detector/batdetect2/')

import batdt2_pipeline
from pipeline import pipeline
from models.bat_call_detector.model_detector import BatCallDetector
from utils.utils import gen_empty_df


LABEL_FOR_GROUPS = {
                    0: 'LF', 
                    1: 'HF'
                    }

def classify_calls_from_file(bd2_predictions, data_params):
    file_path = Path(data_params['audio_file'])
    audio_file = sf.SoundFile(file_path)
    fs = audio_file.samplerate
    num_frames = audio_file.frames

    # When batdetect2 detection thresholds < 0.05, detections provided range from 0 to 128kHz (the upper limit of the resampled file)
    # This is BAD and not sure why batdetect2 does not only provide detections within the range of the original file.
    valid_freqs = bd2_predictions['high_freq']<=(fs/2)
    bd2_predictions_filter1 = bd2_predictions[valid_freqs].copy()

    # For some reason there are also detections that are outside of the chunk's duration
    valid_times = bd2_predictions_filter1['end_time']<=(num_frames/fs)
    bd2_predictions_filter2 = bd2_predictions_filter1[valid_times].copy()
    call_signals, dets = batdt2_pipeline.open_and_get_call_info(audio_file, bd2_predictions_filter2)

    all_dets_including_invalids = pd.concat([dets, bd2_predictions[~(valid_freqs&valid_times)].copy()])
    return all_dets_including_invalids

def apply_model(file_mapping):
    """
    Runs the batdetect2 model on a single provided audio segmens and corrects the offsets according the segment.

    Parameters
    ------------
    file_mappings : `List`
        - List of dictionaries generated by initialize_mappings()

    Returns
    ------------
    corrected_bd_dets : `pandas.DataFrame`
        - A DataFrame of detections that will also be saved in the provided output_dir under the above csv_name
        - 7 columns in this DataFrame: start_time, end_time, low_freq, high_freq, detection_confidence, event, input_file
        - Detections are always specified w.r.t their input_file; earliest start_time can be 0 and latest end_time can be 1795.
        - Events are always "Echolocation" as we are using a model that only detects search-phase calls.
    """

    bd_dets = file_mapping['model']._run_batdetect(file_mapping['audio_seg']['audio_file'])
    bd_preds_classed = classify_calls_from_file(bd_dets, file_mapping['audio_seg'])
    corrected_bd_dets = pipeline._correct_annotation_offsets(
                                                            bd_preds_classed,
                                                            file_mapping['original_file_name'],
                                                            file_mapping['audio_seg']['offset']
                                                            )

    return corrected_bd_dets

def apply_models(file_path_mappings, cfg):
    """
    Runs the batdetect2 model to detect bat search-phase calls in the provided audio segments and saves detections into a dataframe

    Parameters
    ------------
    file_mappings : `List`
        - List of dictionaries generated by initialize_mappings()
    cfg : `dict`
        - A dictionary of pipeline parameters:
        - models is the models in the pipeline that are being used.

    Returns
    ------------
    bd_preds : `pandas.DataFrame`
        - A DataFrame of detections that will also be saved in the provided output_dir under the above csv_name
        - 7 columns in this DataFrame: start_time, end_time, low_freq, high_freq, detection_confidence, event, input_file
        - Detections are always specified w.r.t their input_file; earliest start_time can be 0 and latest end_time can be 1795.
        - Events are always "Echolocation" as we are using a model that only detects search-phase calls.
    """

    torch.set_num_threads(1)
    process_pool = multiprocessing.Pool(cfg['num_processes'])

    bd_dets = tqdm(
            process_pool.imap(batdt2_pipeline.apply_model, file_path_mappings, chunksize=1), 
            desc=f"Applying BatDetect2",
            total=len(file_path_mappings),
        )
    
    bd_preds = gen_empty_df() 
    bd_preds = pd.concat(bd_dets, ignore_index=True)

    # median_peak_HF_freq = bd_preds[bd_preds['KMEANS_CLASSES']=='HF']['peak_frequency'].median()
    # median_peak_LF_freq = bd_preds[bd_preds['KMEANS_CLASSES']=='LF']['peak_frequency'].median()
    # print(f'Median LF frequency in File: {median_peak_LF_freq}')
    # print(f'Median HF frequency in File: {median_peak_HF_freq}')
    # lf_inds = (bd_preds['peak_frequency']<median_peak_LF_freq+7000)&(bd_preds['peak_frequency']>median_peak_LF_freq-7000)
    # hf_inds = (bd_preds['peak_frequency']>median_peak_HF_freq-7000)

    # lf_dets = bd_preds[lf_inds&(bd_preds['KMEANS_CLASSES']=='LF')]
    # hf_dets = bd_preds[hf_inds&(bd_preds['KMEANS_CLASSES']=='HF')]

    # all_dets = pd.concat([hf_dets, lf_dets]).sort_index()
    return bd_preds

def delete_segment(path):
    path['audio_file'].unlink(missing_ok=False)

if __name__ == '__main__':
    wav_filename = '20220826_070000'
    site = 'Central'
    plot_file = Path(f'{Path.home()}/Documents/{wav_filename}/input/{wav_filename}.WAV')

    save_dir = Path(f'{Path.home()}/Documents/20241228_detection_threshold_sweep/bd2__det_thresh_sweep_{wav_filename}')
    save_file_name = f"bd2__{plot_file.name.split('.')[0]}"
    save_dir.mkdir(parents=True, exist_ok=True)

    packages_to_chunk = []
    chunk_instructions_and_files = dict()
    chunk_instructions_and_files['audio_file'] = plot_file
    chunk_instructions_and_files['tmp_dir'] = save_dir
    chunk_instructions_and_files['start_time'] = 0.0
    chunk_instructions_and_files['segment_duration'] = 30.0
    packages_to_chunk+=[chunk_instructions_and_files]

    cfg=dict()
    cfg['num_processes'] = multiprocessing.cpu_count()
    parallel_sg_start = time.time()
    torch.set_num_threads(1)
    ctx = multiprocessing.get_context("spawn")
    pool = ctx.Pool(processes=cfg['num_processes'])
    segmented_file_paths = (tqdm(pool.imap(batdt2_pipeline.generate_segments_parallel, packages_to_chunk, chunksize=1), 
                    desc=f"Segmenting Files", total=len(packages_to_chunk),))
    segmented_file_paths = np.concatenate(list(segmented_file_paths))
    parallel_sg_end = time.time()

    increment = 0.01
    for thresh in np.arange(0.05, 0.6+increment, increment):
        args = dict()
        args['detection_threshold'] = thresh
        args['chunk_size'] = 2

        cfg["time_expansion_factor"] = 1.0
        # Offset (seconds) from the beginning of the audio file to start processing
        cfg["start_time"] = 0.0
        # Input audio is divided into segments of this duration (seconds), each processed individually
        cfg["segment_duration"] = 30.0
        cfg["models"] = [BatCallDetector(detection_threshold=args['detection_threshold'],
                                        spec_slices=False,
                                        chunk_size=args['chunk_size'], 
                                        model_path=f"{Path(__file__).parent}/../src/models/bat_call_detector/batdetect2/models/Net2DFast_UK_same.pth.tar",
                                        time_expansion_factor=1.0,
                                        quiet=False,
                                        cnn_features=True,
                                        peak_distance=0.05,
                                        peak_threshold=0.25,
                                        template_dict_path=f"{Path(__file__).parent}/../src/models/bat_call_detector/templates/template_dict.pickle",
                                        num_matches_threshold=2,
                                        buzz_feed_range=0.15,
                                        alpha=1)]

        file_path_mappings = batdt2_pipeline.initialize_mappings(segmented_file_paths, cfg)
        parallel_rm_start = time.time()
        bd_preds = apply_models(file_path_mappings, cfg)
        parallel_rm_end = time.time()

        print(f'Time taken to generate segments {parallel_sg_end-parallel_sg_start}')
        print(f'Parallel BatDetect2 time: {parallel_rm_end-parallel_rm_start}')
        print(f'Total pipeline time: {parallel_rm_end-parallel_sg_start}')

        ones = int(args['detection_threshold'])
        decimals = int(round(100*(args['detection_threshold']), 1) % 100)
        threshold_tag = f"threshold{ones}p{decimals:02}"
        save_loc = Path(f"bd2__{threshold_tag}_chunksize{int(args['chunk_size'])}_{plot_file.name.split('.')[0]}.csv")
        print("saving to", (save_dir/save_loc))
        bd_preds.to_csv((save_dir/save_loc))

    parallel_del_start = time.time()
    torch.set_num_threads(1)
    ctx = multiprocessing.get_context("spawn")
    pool = ctx.Pool(processes=cfg['num_processes'])
    segmented_file_paths = (tqdm(pool.imap(delete_segment, segmented_file_paths, chunksize=1), 
                    desc=f"Deleting Files", total=len(packages_to_chunk),))
    segmented_file_paths = list(segmented_file_paths)
    parallel_del_end = time.time()


