import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

import time
from pathlib import Path

import soundfile as sf
import torch
from tqdm import tqdm
from torch import multiprocessing

import sys

# append the path of the
# parent directory
sys.path.append(f'{Path(__file__).parent}/..')
sys.path.append(f'{Path(__file__).parent}/../src/')
sys.path.append(f'{Path(__file__).parent}/../src/models/bat_call_detector/batdetect2/')

import batdt2_pipeline
from pipeline import pipeline
from models.bat_call_detector.model_detector import BatCallDetector
from utils.utils import gen_empty_df


LABEL_FOR_GROUPS = {
                    0: 'LF', 
                    1: 'HF'
                    }

def apply_model(file_mapping):
    """
    Runs the batdetect2 model on a single provided audio segmens and corrects the offsets according the segment.

    Parameters
    ------------
    file_mappings : `List`
        - List of dictionaries generated by initialize_mappings()

    Returns
    ------------
    corrected_bd_dets : `pandas.DataFrame`
        - A DataFrame of detections that will also be saved in the provided output_dir under the above csv_name
        - 7 columns in this DataFrame: start_time, end_time, low_freq, high_freq, detection_confidence, event, input_file
        - Detections are always specified w.r.t their input_file; earliest start_time can be 0 and latest end_time can be 1795.
        - Events are always "Echolocation" as we are using a model that only detects search-phase calls.
    """

    bd_dets = file_mapping['model']._run_batdetect(file_mapping['audio_seg']['audio_file'])
    corrected_bd_dets = pipeline._correct_annotation_offsets(
                                                            bd_dets,
                                                            file_mapping['original_file_name'],
                                                            file_mapping['audio_seg']['offset']
                                                            )

    return corrected_bd_dets

def apply_models(file_path_mappings, cfg):
    """
    Runs the batdetect2 model to detect bat search-phase calls in the provided audio segments and saves detections into a dataframe

    Parameters
    ------------
    file_mappings : `List`
        - List of dictionaries generated by initialize_mappings()
    cfg : `dict`
        - A dictionary of pipeline parameters:
        - models is the models in the pipeline that are being used.

    Returns
    ------------
    bd_preds : `pandas.DataFrame`
        - A DataFrame of detections that will also be saved in the provided output_dir under the above csv_name
        - 7 columns in this DataFrame: start_time, end_time, low_freq, high_freq, detection_confidence, event, input_file
        - Detections are always specified w.r.t their input_file; earliest start_time can be 0 and latest end_time can be 1795.
        - Events are always "Echolocation" as we are using a model that only detects search-phase calls.
    """

    torch.set_num_threads(1)
    process_pool = multiprocessing.Pool(cfg['num_processes'])

    bd_dets = tqdm(
            process_pool.imap(apply_model, file_path_mappings, chunksize=1), 
            desc=f"Applying BatDetect2",
            total=len(file_path_mappings),
        )
    
    bd_preds = gen_empty_df() 
    bd_preds = pd.concat(bd_dets, ignore_index=True)

    return bd_preds

def delete_segment(path):
    path['audio_file'].unlink(missing_ok=False)

if __name__ == '__main__':
    file_sites = {'20220730_053000':'Carp',
                '20220826_070000':'Central',
                '20220727_083000':'Foliage',
                '20220829_090000':'Foliage'}
    file_keys = list(file_sites.keys())
    for wav_filename in file_keys:
        site = file_sites[wav_filename]
        file_path = Path(f'{Path.home()}/Documents/mila-human-wav-txt/{wav_filename}.WAV')

        save_dir = Path(f'{Path(__file__).parent}/20241230__detection_threshold_sweep_results')
        save_dir.mkdir(parents=True, exist_ok=True)

        packages_to_chunk = []
        chunk_instructions_and_files = dict()
        chunk_instructions_and_files['audio_file'] = file_path
        chunk_instructions_and_files['tmp_dir'] = save_dir
        chunk_instructions_and_files['start_time'] = 0.0
        chunk_instructions_and_files['segment_duration'] = 30.0
        packages_to_chunk+=[chunk_instructions_and_files]

        cfg=dict()
        cfg['num_processes'] = multiprocessing.cpu_count()
        parallel_sg_start = time.time()
        torch.set_num_threads(1)
        ctx = multiprocessing.get_context("spawn")
        pool = ctx.Pool(processes=cfg['num_processes'])
        segmented_file_paths = (tqdm(pool.imap(batdt2_pipeline.generate_segments_parallel, packages_to_chunk, chunksize=1), 
                        desc=f"Segmenting Files", total=len(packages_to_chunk),))
        segmented_file_paths = np.concatenate(list(segmented_file_paths))
        parallel_sg_end = time.time()

        args = dict()
        args['detection_threshold'] = 0.00
        args['chunk_size'] = 2

        cfg["time_expansion_factor"] = 1.0
        # Offset (seconds) from the beginning of the audio file to start processing
        cfg["start_time"] = 0.0
        # Input audio is divided into segments of this duration (seconds), each processed individually
        cfg["segment_duration"] = 30.0
        cfg["models"] = [BatCallDetector(detection_threshold=args['detection_threshold'],
                                        spec_slices=False,
                                        chunk_size=args['chunk_size'], 
                                        model_path=f"{Path(__file__).parent}/../src/models/bat_call_detector/batdetect2/batdetect2/models/Net2DFast_UK_same.pth.tar",
                                        time_expansion_factor=1.0,
                                        quiet=False,
                                        cnn_features=True,
                                        peak_distance=0.05,
                                        peak_threshold=0.25,
                                        template_dict_path=f"{Path(__file__).parent}/../src/models/bat_call_detector/templates/template_dict.pickle",
                                        num_matches_threshold=2,
                                        buzz_feed_range=0.15,
                                        alpha=1)]

        file_path_mappings = batdt2_pipeline.initialize_mappings(segmented_file_paths, cfg)
        parallel_rm_start = time.time()
        bd_preds = apply_models(file_path_mappings, cfg)
        parallel_rm_end = time.time()

        print(f'Time taken to generate segments {parallel_sg_end-parallel_sg_start}')
        print(f'Parallel BatDetect2 time: {parallel_rm_end-parallel_rm_start}')
        print(f'Total pipeline time: {parallel_rm_end-parallel_sg_start}')

        ones = int(args['detection_threshold'])
        decimals = int(round(100*(args['detection_threshold']), 1) % 100)
        threshold_tag = f"threshold{ones}p{decimals:02}"
        save_loc = Path(f"bd2__{threshold_tag}_chunksize{int(args['chunk_size'])}_{wav_filename}.csv")
        print("saving to", (save_dir/save_loc))
        bd_preds.to_csv((save_dir/save_loc))

        parallel_del_start = time.time()
        torch.set_num_threads(1)
        ctx = multiprocessing.get_context("spawn")
        pool = ctx.Pool(processes=cfg['num_processes'])
        segmented_file_paths = (tqdm(pool.imap(delete_segment, segmented_file_paths, chunksize=1), 
                        desc=f"Deleting Files", total=len(packages_to_chunk),))
        segmented_file_paths = list(segmented_file_paths)
        parallel_del_end = time.time()


