import numpy as np
import pandas as pd
import datetime as dt
import soundfile as sf

import dask.dataframe as dd
from pathlib import Path
import re

import torch
from tqdm import tqdm
from torch import multiprocessing

import fsspec
import sys

# append the path of the
# parent directory
sys.path.append(f'{Path(__file__).parent}/..')
sys.path.append(f'{Path(__file__).parent}/../src/')
sys.path.append(f'{Path(__file__).parent}/../src/models/bat_call_detector/batdetect2/')

import batdt2_pipeline
from cfg import get_config
from pipeline import pipeline
from models.bat_call_detector.model_detector import BatCallDetector
from utils.utils import gen_empty_df


def generate_segments_for_osn(package_to_chunk):
    """
    Segments audio file into clips of duration length and saves them to output/tmp folder.
    Allows detection model to be run on segments instead of entire file as recommended.
    These segments will be deleted from the output/tmp folder after detections have been generated.

    Parameters
    ------------
    audio_file : `pathlib.Path`
        - The path to an audio_file from the input directory provided in the command line
    output_dir : `pathlib.Path`
        - The path to the tmp folder that saves all of our segments.
    start_time : `float`
        - The time at which the segments will start being generated from within the audio file
    duration : `float`
        - The duration of all segments generated from the audio file.

    Returns
    ------------
    output_files : `List`
        - The path (a str) to each generated segment of the given audio file will be stored in this list.
        - The offset of each generated segment of the given audio file will be stored in this list.
        - Both items are stored in a dict{} for each generated segment.
    """

    output_files = []
    fs = fsspec.filesystem('s3', anon=True, client_kwargs={'endpoint_url': 'https://sdsc.osn.xsede.org'})
    file = fs.open(path=package_to_chunk['audio_file'])
    if file.details['size']>0:
        ip_audio = sf.SoundFile(file)

        sampling_rate = ip_audio.samplerate
        # Convert to sampled units
        ip_start = int(package_to_chunk['start_time'] * sampling_rate)
        ip_duration = int(package_to_chunk['segment_duration'] * sampling_rate)
        ip_end = ip_audio.frames

        # for the length of the duration, process the audio into duration length clips
        for sub_start in range(ip_start, ip_end, ip_duration):
            sub_end = np.minimum(sub_start + ip_duration, ip_end)

            # For file names, convert back to seconds 
            op_file = package_to_chunk['audio_file'].name.replace(" ", "_")
            start_seconds =  sub_start / sampling_rate
            end_seconds =  sub_end / sampling_rate
            op_file_en = "__{:.2f}".format(start_seconds) + "_" + "{:.2f}".format(end_seconds)
            op_file = op_file[:-4] + op_file_en + ".wav"
            
            op_path = package_to_chunk['tmp_dir'] / op_file
            output_files.append({
                "input_filepath": package_to_chunk['input_filepath'],
                "audio_file": op_path, 
                "offset":  package_to_chunk['start_time'] + (sub_start/sampling_rate),
            })
            
            if (not(op_path.exists())):
                sub_length = sub_end - sub_start
                ip_audio.seek(sub_start)
                op_audio = ip_audio.read(sub_length)
                sf.write(op_path, op_audio, sampling_rate, subtype='PCM_16')
        
    return output_files 

def apply_model(file_mapping):
    """
    Runs the batdetect2 model on a single provided audio segmens and corrects the offsets according the segment.

    Parameters
    ------------
    file_mappings : `List`
        - List of dictionaries generated by initialize_mappings()

    Returns
    ------------
    corrected_bd_dets : `pandas.DataFrame`
        - A DataFrame of detections that will also be saved in the provided output_dir under the above csv_name
        - 7 columns in this DataFrame: start_time, end_time, low_freq, high_freq, detection_confidence, event, input_file
        - Detections are always specified w.r.t their input_file; earliest start_time can be 0 and latest end_time can be 1795.
        - Events are always "Echolocation" as we are using a model that only detects search-phase calls.
    """

    bd_dets = file_mapping['model']._run_batdetect(file_mapping['audio_seg']['audio_file'])
    corrected_bd_dets = pipeline._correct_annotation_offsets(
                                                            bd_dets,
                                                            file_mapping['original_file_name'],
                                                            file_mapping['audio_seg']['offset']
                                                            )

    return corrected_bd_dets

def delete_segment(path):
    path['audio_file'].unlink(missing_ok=False)


def get_params_relevant_to_data_at_location(cfg):
    data_params = dict()
    data_params['site'] = cfg['site']
    print(f"Searching for files from {cfg['site']} in {cfg['year']} recording season")

    hard_drive_df = dd.read_csv(f'{Path(__file__).parent}/../output_dir/ubna_data_*_collected_audio_records.csv', dtype=str).compute()
    if 'Unnamed: 0' in hard_drive_df.columns:
        hard_drive_df.drop(columns='Unnamed: 0', inplace=True)
    hard_drive_df["datetime_UTC"] = pd.DatetimeIndex(hard_drive_df["datetime_UTC"])
    hard_drive_df.set_index("datetime_UTC", inplace=True)
    
    files_from_location = filter_df_with_location(hard_drive_df, cfg)
    data_params['output_dir'] = cfg["output_dir"] / (data_params["site"].split()[0])
    print(f"Will save csv file to {data_params['output_dir']}")

    data_params['ref_audio_files'] = sorted(list(files_from_location["file_path"].apply(lambda x : Path(x)).values))
    file_status_cond = files_from_location["file_status"] == "Usable for detection"
    file_duration_cond = np.isclose(files_from_location["file_duration"].astype('float'), cfg['duration'])
    good_location_df = files_from_location.loc[file_status_cond&file_duration_cond]
    data_params['good_audio_files'] = sorted(list(good_location_df["file_path"].apply(lambda x : Path(x)).values))

    if data_params['good_audio_files'] == data_params['ref_audio_files']:
        print("All files from deployment session good!")
    else:
        print("Error files exist!")

    print(f"Will be looking at {len(data_params['good_audio_files'])} files from {data_params['site']}")

    return good_location_df, data_params


def filter_df_with_location(ubna_data_df, cfg):
    site_name_cond = ubna_data_df["site_name"] == cfg['site']
    file_year_cond = ubna_data_df.index.year == (dt.datetime.strptime(cfg['year'], '%Y')).year
    file_july_cond = ubna_data_df.index.month == (dt.datetime.strptime('July', '%B')).month
    file_august_cond = ubna_data_df.index.month == (dt.datetime.strptime('August', '%B')).month
    file_september_cond = ubna_data_df.index.month == (dt.datetime.strptime('September', '%B')).month
    file_october_cond = ubna_data_df.index.month == (dt.datetime.strptime('October', '%B')).month
    file_month_cond1 = np.logical_or(file_july_cond, file_august_cond)
    file_month_cond2 = np.logical_or(file_september_cond, file_october_cond)
    file_month_cond = np.logical_or(file_month_cond1, file_month_cond2)

    minute_cond = np.logical_or((ubna_data_df.index).minute == 30, (ubna_data_df.index).minute == 0)
    datetime_cond = np.logical_and((ubna_data_df.index).second == 0, minute_cond)
    file_error_cond = np.logical_and((ubna_data_df["file_duration"]!='File has no comment due to error!'), (ubna_data_df["file_duration"]!='File has no Audiomoth-related comment'))
    all_errors_cond = np.logical_and((ubna_data_df["file_duration"]!='Is empty!'), file_error_cond)
    file_date_cond = np.logical_and(file_year_cond, file_month_cond)

    filtered_location_df = ubna_data_df.loc[site_name_cond&datetime_cond&file_date_cond&all_errors_cond].sort_index()
    filtered_location_nightly_df = filtered_location_df.between_time(cfg['recording_start'], cfg['recording_end'], inclusive="left")

    return filtered_location_nightly_df

if __name__ == '__main__':
    cfg = get_config()
    cfg["site"] = 'Carp Pond'
    cfg["year"] = '2022'
    cfg['recording_start'] = '00:00'
    cfg['recording_end'] = '16:00'
    cfg['duration'] = 1795
    cfg["output_dir"] = Path(f'{Path.home()}/Documents/bd2_dets_20241226_thresh0p20/output_dir')
    cfg["tmp_dir"] = Path(f'{Path.home()}/Documents/bd2_dets_20241226_thresh0p20/output')
    cfg["skip_existing"] = False
    cfg['should_csv'] = True
    cfg["num_processes"] = multiprocessing.cpu_count()

    good_location_df, data_params = get_params_relevant_to_data_at_location(cfg)
    bd_preds = pd.DataFrame()

    if not data_params['output_dir'].is_dir():
        data_params['output_dir'].mkdir(parents=True, exist_ok=True)
    if not cfg['tmp_dir'].is_dir():
        cfg['tmp_dir'].mkdir(parents=True, exist_ok=True)

    for file in data_params['good_audio_files']:
        cfg["csv_filename"] = f"bd2__{data_params['site'].split()[0]}_{file.name.split('.')[0]}"
        if cfg['skip_existing'] & (data_params['output_dir'] / f"{cfg['csv_filename']}.csv").is_file():
            print(f'Detections for this {file.name} have already been generated!')
        else:
            print(f"Generating detections for {file.name}")
            recover_folder = good_location_df.loc[good_location_df['file_path'] == str(file), 'recover_folder'].values[0]
            audiomoth_folder = good_location_df.loc[good_location_df['file_path'] == str(file), "sd_card_num"].values[0]
            print(f"This file exists under {recover_folder}/UBNA_{audiomoth_folder}")

            file_path = '/'.join(file.parts[2:])
            cleaned_path = re.sub(r"(ubna_data_\d+)_mir", r"\1", file_path)
            osn_file_path = Path(f'bio230143-bucket01/{cleaned_path}')
            
            packages_to_chunk = []
            chunk_instructions_and_files = dict()
            chunk_instructions_and_files['audio_file'] = osn_file_path
            chunk_instructions_and_files['input_filepath'] = file
            chunk_instructions_and_files['tmp_dir'] = cfg['tmp_dir']
            chunk_instructions_and_files['start_time'] = 0.0
            chunk_instructions_and_files['segment_duration'] = 30.0
            packages_to_chunk+=[chunk_instructions_and_files]

            torch.set_num_threads(64)
            ctx = multiprocessing.get_context("spawn")
            pool = ctx.Pool(processes=cfg["num_processes"])
            segmented_file_paths = (tqdm(pool.imap(generate_segments_for_osn, packages_to_chunk, chunksize=1), 
                            desc=f"Segmenting Files", total=len(packages_to_chunk),))
            segmented_file_paths = np.concatenate(list(segmented_file_paths))

            cfg["time_expansion_factor"] = 1.0
            # Offset (seconds) from the beginning of the audio file to start processing
            cfg["start_time"] = 0.0
            # Input audio is divided into segments of this duration (seconds), each processed individually
            cfg["segment_duration"] = 30.0
            cfg["models"] = [BatCallDetector(detection_threshold=0.2,
                                            spec_slices=False,
                                            chunk_size=2, 
                                            model_path=f"{Path(__file__).parent}/../src/models/bat_call_detector/batdetect2/models/Net2DFast_UK_same.pth.tar",
                                            time_expansion_factor=1.0,
                                            quiet=False,
                                            cnn_features=True,
                                            peak_distance=0.05,
                                            peak_threshold=0.25,
                                            template_dict_path=f"{Path(__file__).parent}/../src/models/bat_call_detector/templates/template_dict.pickle",
                                            num_matches_threshold=2,
                                            buzz_feed_range=0.15,
                                            alpha=1)]
            file_path_mappings = batdt2_pipeline.initialize_mappings(segmented_file_paths, cfg)
                    
            torch.set_num_threads(1)
            pool = multiprocessing.Pool(processes=cfg['num_processes'])
            print(f'Parsing {len(file_path_mappings)} chunks with {cfg["num_processes"]} processors and chunksize 1 and {torch.get_num_threads()} threads per processor')
            bd_dets = tqdm(pool.imap(apply_model, file_path_mappings, chunksize=1), 
                        desc=f"Applying BatDetect2", total=len(file_path_mappings))
            bd_preds = gen_empty_df() 
            bd_preds = pd.concat(bd_dets, ignore_index=True)
            bd_preds["Site name"] = data_params['site']
            bd_preds["Recover Folder"] = recover_folder
            bd_preds["SD Card"] = audiomoth_folder
            bd_preds["File Duration"] = f'{cfg["duration"]}'
            batdt2_pipeline._save_predictions(bd_preds, data_params['output_dir'], cfg)

            torch.set_num_threads(64)
            ctx = multiprocessing.get_context("spawn")
            pool = ctx.Pool(processes=cfg['num_processes'])
            segmented_file_paths = (tqdm(pool.imap(delete_segment, segmented_file_paths, chunksize=1), 
                            desc=f"Deleting Files", total=len(packages_to_chunk),))
            segmented_file_paths = list(segmented_file_paths)